image: docker:latest

services:
    - docker:dind

stages:
    - test_client
    - trigger_tests

before_script:
    - apk update
    - apk upgrade
    - apk --no-cache add --update curl python2 python2-dev python3 python3-dev musl-dev gcc libffi-dev git bash nss-tools openssl make py-pip
    - pip install docker-compose
    - git submodule update --init --recursive

test_client:
    stage: test_client
    script:
        - tests/test_client.sh

trigger_tests:
    stage: trigger_tests
    script:
        - curl -X POST -F token=$TEST_TRIGGER -F ref=master https://gitlab.com/api/v4/projects/10857649/trigger/pipeline
