image: docker:latest

services:
    - docker:dind

stages:
    - test_client
    - trigger_tests

before_script:
    - apk update
    - apk upgrade
    - apk --no-cache add --update openssl-dev curl python2 python2-dev python3 python3-dev musl-dev gcc libffi-dev git bash nss-tools openssl make py-pip
    - pip install docker-compose
    - git submodule update --init --recursive

test_client:
    stage: test_client
    script:
        - tests/test_client.sh
